name: Test Backend

on:
  push:
    branches: [main]
  pull_request:
    branches : [main]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Amazon Corretto JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build and Test with Maven
        run: mvn -B verify sonar:sonar
          -Dsonar.projectKey=theonlyymanal_Devops-CI-CD
          -Dsonar.organization=theonlyymanal
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          --file ./simple-api/pom.xml

